on:
  push:
    branches:
      - main

jobs: 
  unit_testing:
    name: Test the code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --coverage --watchAll=false

  build:
    name: Build and Deploy to DockerHub
    needs: [unit_testing]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker build for testing
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/olumoko_image:latest
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/olumoko_image:latest ${{ secrets.DOCKERHUB_USERNAME }}/olumoko_image:${{ github.run_number }}

      - name: docker build testing
        run: | 
          docker images
           docker run --name my-node-app -d \
            -p 3000:3000 \
            ${{ secrets.DOCKERHUB_USERNAME }}/olumoko_image:latest
            
          export IP=$(docker inspect -f '{{range .NetworkSetings.Networks}}{{.IPAddress}}{{end}}' my-node-app)
          echo $IP

        - name: Wait for container to start
        run: sleep 10  # Adjust this wait time based on your container startup time
      
      - name: Run curl command
        run: curl -v http://127.0.0.1:3000
      
      - name: Stop Docker container
        run: docker stop my-node-app






         # #curl -q -O - 127.0.0.1:3000

      #- name: Push images to Docker Hub
        #run: |
          #docker push ${{ secrets.DOCKERHUB_USERNAME }}/olumoko_image:latest
          #docker push ${{ secrets.DOCKERHUB_USERNAME }}/olumoko_image:${{ github.run_number }}




